CREATE DATABASE first_lab;
USE first_lab;

CREATE TABLE student_records (
student_id VARCHAR(10) NOT NULL PRIMARY KEY,
student_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
course VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);